name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  uv-ci-tests-kata-numbers:
    name: uv-ci-tests-kata-numbers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest
